In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV created in part one...

city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df

,City_ID,City,Country,Date,Lat,lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Port Elizabeth,ZA,2022-07-21- 00:03;07,-33.9180,25.5701,55.31,91,100,4.00
1,1,Tuktoyaktuk,CA,2022-07-21- 00:01;53,69.4541,-133.0374,45.12,87,100,9.15
2,2,Airai,TL,2022-07-21- 00:03;08,-8.9266,125.4092,63.37,80,89,3.76
3,3,Pacific Grove,US,2022-07-21- 00:02;56,36.6177,-121.9166,79.25,82,40,11.50
4,4,Antofagasta,CL,2022-07-21- 00:00;12,-23.6500,-70.4000,56.97,82,90,1.30
...,...,...,...,...,...,...,...,...,...,...
537,537,Bay Roberts,CA,2022-07-21- 00:16;54,47.5999,-53.2648,65.34,91,88,8.99
538,538,Shimoda,JP,2022-07-21- 00:16;54,34.6667,138.9500,79.16,77,83,7.83
539,539,Tautira,PF,2022-07-21- 00:12;17,-17.7333,-149.1500,76.32,73,14,9.82
540,540,Fenoarivo,MG,2022-07-21- 00:16;55,-18.9330,47.4354,51.87,100,75,11.50
541,541,Darhan,MN,2022-07-21- 00:16;56,49.4867,105.9228,59.99,67,87,6.42

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Create a Maximum Temperature Heatmap

In [5]:
# configure gmaps to use my Google API key
gmaps.configure(api_key=g_key)

In [6]:
### The general syntax for creating a heatmap is as follows

## Assign the locations to an array of latitude and longitude pairs.

# locations = [latitute, longitude]

# ## Assign the weights variable to some values.

# temperatures = # an array of length equal to the locations array length

# ## Assign the figure variable to the gmaps.figure() attribute.

# fig = gmaps.figure()

# ## Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.

# heatmap_layer = gmaps.heatmap_layer(locations, weights=temperatures)

# ## Add the heatmap layer:

# fig.add_layer(heatmap_layer)

# ## Call the figure to plot the data

# fig

In [7]:
# # Heatmap of temperature

# # Get the latiture and longitude

# locations = city_data_df[["Lat", "lng"]]

# # Get the maximum temperature

# max_temp = city_data_df["Max Temp"]

# # Assign the figure variable.

# fig = gmaps.figure()

# # Assign the heatmap variable

# heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)

# # Add the heatmap layer

# fig.add_layer(heat_layer)

# # Call the figure to plot the data

# fig

In [8]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [9]:
# Heatmap of temperature
# Get the latitude and longitude.

locations = city_data_df[["Lat", "lng"]]

# Get the maximum temperature.

max_temp = city_data_df["Max Temp"]

# Assign the figure variable.

fig = gmaps.figure()

# Assign the heatmap variable.

heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])

# Add the heatmap layer.

fig.add_layer(heat_layer)

# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Heatmap of temperature with the center and zoom level , so we only show one map of earth...
# Get the latitude and longitude.

locations = city_data_df[["Lat", "lng"]]

# Get the maximum temperature.

max_temp = city_data_df["Max Temp"]

# Assign the figure variable.

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.

heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp],
                                 dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.

fig.add_layer(heat_layer)

# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Heatmap of percent humidity

locations = city_data_df[["Lat", "lng"]]
humidity = city_data_df["Humidity"]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

heat_layer = gmaps.heatmap_layer(locations, weights=humidity,
                                 dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Heatmap of percent cloudiness

locations = city_data_df[["Lat", "lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# Heatmap of wind speed:

locations = city_data_df[["Lat", "lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Ask the customer to add a minimum and maximum temperature value.

min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [17]:
# Filter the dataset to find the cities that fit the criteria.

preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,lng,Max Temp,Humidity,Cloudiness,Wind Speed
3,3,Pacific Grove,US,2022-07-21- 00:02;56,36.6177,-121.9166,79.25,82,40,11.50
13,13,Georgetown,MY,2022-07-21- 00:03;06,5.4112,100.3354,80.53,85,20,0.00
17,17,Katsuura,JP,2022-07-21- 00:03;12,35.1333,140.3000,80.35,78,72,8.84
19,19,Roma,US,2022-07-21- 00:02;48,43.2128,-75.4557,86.86,66,0,5.75
21,21,Victoria,HK,2022-07-21- 00:02;52,22.2855,114.1577,89.96,82,16,5.01
25,25,Atuona,PF,2022-07-21- 00:03;14,-9.8000,-139.0333,77.56,75,3,14.36
40,40,Hithadhoo,MV,2022-07-21- 00:02;32,-0.6000,73.0833,81.09,68,99,3.00
41,41,Hilo,US,2022-07-21- 00:01;02,19.7297,-155.0900,84.27,81,52,4.00
44,44,Hasaki,JP,2022-07-21- 00:03;20,35.7333,140.8333,84.29,76,76,6.44
45,45,The Valley,AI,2022-07-21- 00:03;20,18.2170,-63.0578,82.09,81,3,22.26

In [18]:
preferred_cities_df.notnull().sum()

City_ID       176
City          176
Country       176
Date          176
Lat           176
lng           176
Max Temp      176
Humidity      176
Cloudiness    176
Wind Speed    176
dtype: int64

In [19]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.

hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

             City Country  Max Temp      Lat       lng Hotel Name
3   Pacific Grove      US     79.25  36.6177 -121.9166
13     Georgetown      MY     80.53   5.4112  100.3354
17       Katsuura      JP     80.35  35.1333  140.3000
19           Roma      US     86.86  43.2128  -75.4557
21       Victoria      HK     89.96  22.2855  114.1577
25         Atuona      PF     77.56  -9.8000 -139.0333
40      Hithadhoo      MV     81.09  -0.6000   73.0833
41           Hilo      US     84.27  19.7297 -155.0900
44         Hasaki      JP     84.29  35.7333  140.8333
45     The Valley      AI     82.09  18.2170  -63.0578

In [20]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [30]:
# Iterate through the DataFrame.

for index, row in hotel_df.iterrows():
    
    # Get the latitude and longitude.
    
    lat = row["Lat"]
    lng = row["lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    

    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [31]:
# Add a heatmap of temperature for the vacation spots.

locations = hotel_df[["Lat", "lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [36]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

In [37]:
# Store the DataFrame Row.

hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [38]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.

locations = hotel_df[["Lat", "lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))